version: "3.8"
services:
  client:
    build: ./client
    container_name: client
    tty: true
  evilserver:
    build: ./evilserver
    container_name: evilserver
    tty: true
  internalservice:
    build: ./internalservice
    container_name: internalservice
    tty: true
